In [2]:
#flower classification using support vector machine(SVM)

In [2]:
#importing libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm, metrics
import numpy as np

In [3]:
#loading the dataset onto a variable
iris=datasets.load_iris()

In [4]:
#Splitting the dataset into features and labels
X=iris.data
y=iris.target

print("X:", X.shape)
print("y:", y.shape)

X: (150, 4)
y: (150,)


In [5]:
#classification attributes
classes=[" Iris Setosa", "Iris Versicolour", "Iris Virginica"]

In [6]:
#splitting the datainto training and test set
X_train, X_test, y_train, y_test=train_test_split(X, y, train_size=0.8)

In [7]:
#Training set
print("Training set:\n\n")
print("X_train:\n", X_train)
print("\ny_train:\n", y_train)

Training set:


X_train:
 [[5.8 2.7 5.1 1.9]
 [5.8 2.6 4.  1.2]
 [6.1 2.8 4.7 1.2]
 [6.7 3.1 5.6 2.4]
 [5.2 3.5 1.5 0.2]
 [6.2 2.8 4.8 1.8]
 [5.6 3.  4.1 1.3]
 [5.1 3.4 1.5 0.2]
 [7.7 2.8 6.7 2. ]
 [6.8 2.8 4.8 1.4]
 [5.  2.  3.5 1. ]
 [5.8 2.7 3.9 1.2]
 [6.5 3.  5.2 2. ]
 [5.1 3.3 1.7 0.5]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.4 2.1]
 [4.9 3.1 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [4.8 3.  1.4 0.1]
 [6.  2.2 4.  1. ]
 [5.4 3.9 1.3 0.4]
 [4.8 3.  1.4 0.3]
 [6.9 3.1 4.9 1.5]
 [5.1 3.7 1.5 0.4]
 [5.2 2.7 3.9 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [5.1 3.5 1.4 0.2]
 [6.4 2.8 5.6 2.1]
 [5.5 3.5 1.3 0.2]
 [5.1 2.5 3.  1.1]
 [7.  3.2 4.7 1.4]
 [4.9 3.1 1.5 0.1]
 [6.6 3.  4.4 1.4]
 [6.3 2.9 5.6 1.8]
 [5.5 2.5 4.  1.3]
 [5.6 2.7 4.2 1.3]
 [4.6 3.6 1.  0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.  4.5 1.5]
 [7.1 3.  5.9 2.1]
 [6.7 3.  5.  1.7]
 [4.8 3.4 1.6 0.2]
 [6.2 2.9 4.3 1.3]
 [4.6 3.4 1.4 0.3]
 [6.  3.  4.8 1.8]
 [6.4 2.9 4.3 1.3]
 [4.9 2.5 4.5 1.7]
 [5.7 2.8 4.5 1.3]
 [5.4 3.7 1.5 0.2]
 [5.7 4.4 1.5 0.4]
 [5.6

In [8]:
#creating a model
model=svm.SVC()

In [9]:
#training the model
model.fit(X_train, y_train)
print(model)

SVC()


In [10]:
#prediction
prediction=model.predict(X_test)
print("\nActual set:\n", y_test.ravel())
print("\nPredictions:\n", prediction)


Actual set:
 [0 1 0 0 1 1 1 2 0 2 0 0 2 2 0 2 2 2 1 1 0 1 1 0 2 1 1 2 2 2]

Predictions:
 [0 2 0 0 1 1 1 2 0 2 0 0 2 2 0 2 2 2 1 1 0 1 1 0 2 1 1 2 2 2]


In [11]:
#wrong predictions
#non zero values are the wrongly predicted outcomes
print("Wrong Outcomes :\n", y_test.ravel()-prediction)

Wrong Outcomes :
 [ 0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [13]:
#accuracy of the model
accuracy=metrics.accuracy_score(y_test, prediction)
print("Accuracy: ", accuracy*100, "%")

Accuracy:  96.66666666666667 %
