In [52]:
#car class prediction using k-nearest neighbors method(kNN)

In [80]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics, svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [81]:
#loading the dataset
data=pd.read_csv(r"C:\Users\Maitreya\JupyterNotebooks\datasets\car.data")
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [82]:
#extracting required features
X=data[['buying', 'maint', 'safety']].values
y=data[['class']]

In [83]:
#converting the data
#X
Le=LabelEncoder()
for i in range(len(X[0])):
    X[:, i]=Le.fit_transform(X[:, i])
    
print("X:\n", X)

#y
label_mapping={
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class']=y['class'].map(label_mapping)
y=np.array(y)

print("\ny:\n", y)

X:
 [[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]

y:
 [[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-83-a62eb665567c>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class']=y['class'].map(label_mapping)


In [84]:
#creating the model
knn=neighbors.KNeighborsClassifier(n_neighbors=25, weights="uniform")
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)
knn.fit(X_train, y_train.ravel())

KNeighborsClassifier(n_neighbors=25)

In [85]:
#car classes
print("Car classes:\n unacc:0, acc:1, good:2, vgood:3")

#prediction and accuracy
prediction=knn.predict(X_test)
print("\nActual set:\n", y_test.ravel())
print("\nPredictions:\n", prediction)

Car classes:
 unacc:0, acc:1, good:2, vgood:3

Actual set:
 [0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 1 0 1 0 1 0 0 0 1 0 1 0 0 3 0 3 1 0 1 1 0 0 1 0 1 0 1 0 0 0 2 1 0 0 0 1 0
 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 2 0 0 0 1 0 0 0 0 0 0 2 0 2 0 0 0 0 0 0 0 0
 1 0 2 0 0 1 1 2 0 2 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 2 1 1 0 1 0 0 0 0 0 0 0 0 0 2 1 1 0 1
 2 0 2 1 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 2 3 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 3 0 0 0 1 0 0 0 2 0 1
 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 3 0 0 0 1
 0 0 1 0 0 0 1 1 1 0 0 0 0 1 0 2 0 0 0 0 1 0 1 2 0 0 0 0 0 0 1 1 0 0 0 1 2
 0 3 1 2 0 1 0 0 0 1 0 0 1]

Predictions:
 [3 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 2 2
 1 0 0 0 0 3 0 0 1 0 1 0 0 0 0 3 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [86]:
#wrong predictions
#non zero values are the wrongly predicted outcomes
print("Wrong Outcomes :\n", y_test.ravel()-prediction)

Wrong Outcomes :
 [-3  0  0 -2  1  0  0  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0 -1
  0  0  0  0 -1  0  0  0  0  0 -1 -2 -2  0  0  1  0  1 -3  0  0  0  0  0
  0  0  3  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  2  1  0 -1  0
  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0
  0  0  0  0  2  0  2  0  0  0  0  0  0  0  0  0 -3  2  0  0  0  0  2 -3
  2  0  0  1  0  0  0  0  1 -1  0  0  0  0  0  0  0  0  0  0 -1  0  0 -1
  0  0 -1  0  1  0  0 -1  0  0  0  0  0  0  0  1  0  0  0  0  0  0 -1  1
  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  1 -1  0 -1  1  0  0  0
 -1  0  0  0  0  1  0  0 -1  1  0  0  0  0  1  1  0  0 -2  0  0  0 -3  0
  0  1  0  0  0  0  2  0  0  0  0  0 -3  0  0  0 -1  1  0  0  0  0  0  1
  0  0  0  0  0  0  0 -1  0  0 -1  0  1  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0 -2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
 -1  0  0  3  0  0 -1  1  0  0  1  0 -3  0  0  0 -1  0  0 -1  0  0  0  0
  0  0  0 -1  0  0  0  0  0  0  0

In [88]:
#accuracy of the model
accuracy=metrics.accuracy_score(y_test, prediction)
print("Accuracy: ", accuracy*100, "%")

Accuracy:  77.45664739884393 %
